version to date and plasma to xfce

diff --git a/archiso/airootfs/usr/local/bin/carli-final b/archiso/airootfs/usr/local/bin/carli-final
--- a/archiso/airootfs/usr/local/bin/carli-final
+++ b/archiso/airootfs/usr/local/bin/carli-final
@@ -32,10 +32,8 @@ rm -r /etc/systemd/system/etc-pacman.d-gnupg.mount
 rm /root/{.automated_script.sh,.zlogin}
 mv /etc/carli-release /etc/lsb-release
 
-#echo "Remove /etc/pacman.d/gnupg"
-#echo "#################################"
-#rm -rf /etc/pacman.d/gnupg/*
-
+#cleanup xfce
+for i in `ls /home/`; do rm -rf /home/$i/Desktop/calamares.desktop || exit 0; done
 
 echo "Permission of root"
 echo "#################################"
